sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

addons:
  apt:
    packages:
    - sox

# command to install dependencies
install:
  - pip install python-coveralls pytest-faulthandler
  - pip install -e .

# command to run tests
script: py.test

after_success:
    - coveralls
